from __future__ import annotations

# Function and language intrinsic names documented for the SRHD 2.1.2500
# RScript runtime.  This deliberately broad registry also contains documented
# runtime variables/properties: accepting one as callable is safer than falsely
# rejecting a valid engine extension, while missing user functions still fail.
RSCRIPT_RUNTIME_CALLS = frozenset(
    {
        "abs", "abshipmodifiers", "acrynlevel", "acrynserie", "actualequiptype", "adddialogblock", "adddialoginject", "adddialogoverride",
        "additemtoplanet", "additemtoship", "additemtoshop", "additemtostorage", "addplanetnews", "advancedadjustmentset", "allshipout", "angle",
        "arctan", "arrangeitems", "arrayadd", "arraychange", "arrayclear", "arraydelete", "arraydim", "arrayfind",
        "arrayfindinsorted", "arrayrandomize", "arraysort", "arraysortpartial", "artefacttypeboosted", "artefacttypeinuse", "arttranclucatortoship", "asteroidgraph",
        "asteroidminerals", "asteroidrespawn", "autobattle", "bioequip", "blazer", "blazerlanding", "blazerselfdestruction", "blockexist",
        "blockimp", "blockmm", "bmspawncondition", "bonuscount", "bonuscustomtag", "bonusisspecial", "bonusname", "bonusnumincfg",
        "bonuspriority", "bonustext", "bonusvalue", "break", "buildcustomruins", "buildlistofmmbypriority", "buildlistofnewships", "buildlistofquestpossiblelocations",
        "buildruins", "buttonclick", "buybigwarrior", "buydomik", "buydomikextremal", "buypirate", "buyranger", "buytranclucator",
        "buytransport", "buywarrior", "cansellitem", "capitalshipstats", "chameleon", "chancetowin", "changeglobalrelationsplanets", "changeglobalrelationsships",
        "changestate", "closecustomform", "coalitiondefeated", "color", "conchangerelationtoranger", "conname", "connear", "constar",
        "constars", "containerfuel", "continue", "controlledsystems", "converttoabship", "coordx", "coordy", "copy",
        "cos", "count", "countbox", "countin", "countreward", "countrewardbynom", "countsas", "countturn",
        "createabship", "createactcodeevent", "createart", "createcustomart", "createcustomcountableitem", "createcustomweapon", "createequipment", "createequipmentwithspecial",
        "creategoods", "createhull", "createmm", "createnodes", "createplanet", "createquestitem", "createzond", "ct",
        "curinfo", "curitem", "currentform", "currentmods", "curship", "curturn", "customartcostcalc", "customartdata",
        "customartsizecalc", "customarttextdata", "customether", "customfaction", "custominterfaceimage", "custominterfacepos", "custominterfaceposz", "custominterfacesize",
        "custominterfacestate", "custominterfacetext", "customlose", "custommissiletype", "customweapontype", "customweapontypes", "customwin", "dadd",
        "daddtext", "damageradius", "danswer", "dchange", "dealdamagetoship", "decaygoods", "delete", "deleteequipment",
        "deleterewardbynom", "deletetags", "deltawin", "dialog", "dist", "dist2star", "distcoords", "disttonearestenemysystem",
        "domikkilledincursystem", "domikprogramm", "domikprogrammdate", "domiksdefeated", "drawlines", "dropitem", "dropiteminsystem", "dropscriptitem",
        "dtext", "dword", "else", "endgame", "endstate", "enginepower", "eqcustomfaction", "eqmodule",
        "eqspecial", "equipmentimagename", "equipments", "ether", "etherdelete", "etheridadd", "etheriddelete", "etherstate",
        "events", "executecodefromstring", "existingzonds", "exit", "exp", "exponent", "extremaltakeoff", "filmflags",
        "filmsound", "findbonusbycustomtag", "findbonusbyname", "findbonusbynameincfg", "finditeminship", "finditeminstorage", "findplanet", "findplanetbyadvancement",
        "findseriesbyname", "findsubstr", "fireweapon", "firstgivemoney", "float", "for", "forcenextday", "forcharactertypes",
        "format", "formchange", "formcurship", "formshipcuritem", "fornpctypes", "frac", "fragility", "fragilityenergy",
        "fragilitymissile", "fragilitysplinter", "free", "freeitem", "freelibrary", "function", "gabstatus", "galaxydifflevels",
        "galaxydominatorresearchmaterial", "galaxydominatorresearchpercent", "galaxyeventdata", "galaxyeventdate", "galaxyevents", "galaxyeventstextdata", "galaxyeventtype", "galaxyholes",
        "galaxymoney", "galaxyptr", "galaxyrangers", "galaxysectors", "galaxyshipid", "galaxystar", "galaxystars", "galaxytechlevel",
        "gallcntrun", "gamedatetxtbyturn", "gcntrun", "generatecodestringfromblock", "getachievementcoallition", "getachievementgirlshire", "getachievementgirlsquest", "getachievementhull",
        "getachievementpiratewin", "getachievementshu", "getartfromship", "getcustomweapondata", "getcustomweaponinfo", "getcustomweaponprimarydamagetype", "getdata", "getequipmentstats",
        "getgalaxygenerationseed", "getgameoptions", "getitemfromplanet", "getitemfromship", "getitemfromshop", "getitemfromstar", "getitemfromstorage", "getitemfromvault",
        "getmaindata", "getnodesfromship", "getnodesfromstorage", "getowner", "getparfromstring", "getparfromtxt", "getplanetorbitprobe", "getprogramm",
        "getrelationplanet", "getscriptnoklingmarksfromstar", "getsectoradjacenttodicea", "getshipexpbytype", "getshiphomeplanet", "getshippiraterank", "getshipplanet", "getshipruins",
        "getshipscriptname", "getstringfromclipboard", "gettalkship", "gettalktype", "getvaluefromscript", "getvariablename", "getvariabletype", "givereward",
        "giverewardbynom", "glastturnrun", "globalrelationsplanets", "globalrelationsships", "goodsadd", "goodsbuyprice", "goodscount", "goodsdrop",
        "goodsruinsforbuy", "goodssellprice", "gotogov", "groupcount", "groupin", "groupis", "groupsetbad", "groupship",
        "grouptoship", "grun", "grunfrom", "gscriptname", "gvideostatus", "haveprogramm", "hit", "hitpoints",
        "holecreate", "holecreate2", "holemamacreate", "holemap", "holestar1", "holestar2", "holeturncreate", "holex1",
        "holex2", "holey1", "holey2", "hulldamage", "hulldamagesuspectibility", "hullgraphsize", "hullhp", "hullseries",
        "hullspecial", "hulltype", "id", "idtohole", "idtoitem", "idtoplanet", "idtoship", "if",
        "imagefirst", "imitatedequiptype", "imitatedhulltype", "importall", "importedfunction", "infos", "injectanswer", "int",
        "interfaceimage", "interfacepos", "interfacesize", "interfacestate", "interfacetext", "inventnewcustomweapon", "ischameleon", "isfilm",
        "isplayer", "isscriptactive", "isshiftctrlpressed", "itemcanbebroken", "itemcharge", "itemcost", "itemcount", "itemdestroy",
        "itemdurability", "itemexist", "itemextraspecials", "itemextraspecialsaddbytype", "itemextraspecialscountbytype", "itemextraspecialsdeletebytype", "itemfragility", "itemfullname",
        "itemimprovement", "itemin", "iteminscript", "itemisbroken", "itemisinset", "itemisinuse", "itemlevel", "itemname",
        "itemonactcode", "itemonusecode", "itemowner", "itemsize", "itemsubrace", "itemtype", "keller", "kellerkill",
        "kellerleave", "kellernewresearch", "launchmissile", "levelscount", "libraryfunction", "linescolor", "linkitemtoscript", "listbox",
        "ln", "loadlibrary", "lockedacryn", "lowercase", "makeshipenterstar", "markrobotsmapasused", "max", "mayaddbonustoeq",
        "messagebox", "messageboxyesno", "min", "missileangle", "missilelive", "missilemaxdamage", "missilemindamage", "missileowner",
        "missilespeed", "missilestar", "missilestorearm", "missiletarget", "missiletype", "missileweaponid", "moduletoequipment", "msgadd",
        "name", "nameprefix", "nearcivilplanet", "nearestgroup", "new", "newarray", "newsadd", "nobridge",
        "nocomeklingtostar", "nodropitem", "nodroptoship", "nojump", "nolanding", "nonrepairable", "nonsearchable", "noscantoship",
        "noshopupdate", "notalktoship", "notargettoship", "notremovable", "nowear", "numberbox", "objecttype", "onkey",
        "onmouseentercode", "onmouseleavecode", "onmouserightclick", "onpresscode", "onusecodeblackhole", "onusecodemissiledef", "onusecodetranclucator", "onusecodetransmitter",
        "opencustomform", "ord", "orderfollowship", "orderforsage", "orderjump", "orderjumphole", "orderlanding", "orderlock",
        "ordermove", "ordernone", "ordertakeoff", "orderteleport", "owner", "parscountfromstring", "pi", "piratetype",
        "piratewin", "planetboostinventions", "planetcurinvention", "planetcurinventionpoints", "planetcustomfaction", "planeteco", "planetextraflags", "planetgetgraph",
        "planetgov", "planetinventionlevel", "planetitems", "planetname", "planetnews", "planetnewsdate", "planetnewstext", "planetnewstype",
        "planetorbitalvelocity", "planetorbitradius", "planetowner", "planetpirateclan", "planetpopulation", "planetrace", "planetsetgoods", "planetsetgraph",
        "planetsize", "planetterrain", "planetterrainexplored", "planettostar", "planetwarriors", "player", "playerbridge", "playerchameleoncharges",
        "playerchameleoncurtype", "playerchameleondetected", "playerdebt", "playerdebtcnt", "playerdebtdate", "playerdeposit", "playerdepositdate", "playerdepositday",
        "playerdepositpercent", "playerdominatorstatistic", "playereqset", "playerimmunity", "playerlogicchameleon", "playermaytakesubcrack", "playermedpolicy", "playerpirates",
        "playerplanetarybattlescompleted", "playerquestinprogress", "playerquestscompleted", "playertranclucators", "portionindiapason", "posautocorrection", "posautocorrectionxcoef", "posautocorrectionycoef",
        "putiteminvault", "questsstatusbynom", "racialrestriction", "radius", "raisepiraterank", "randomize", "randseed", "rangerbasenodes",
        "rangerexcludedfromrating", "rangerplaceinrating", "rangerscapital", "rangerstatus", "ref", "relationtoranger", "relationtoship", "releaseitemfromscript",
        "resourceexist", "result", "rnd", "rndobject", "robotsupport", "round", "roundto", "ruinsallowmodernization",
        "ruinschangetype", "ruinsmicromodulechain", "runchildform", "saferadius", "scriptactionsrun", "scriptitemactiontype", "scriptitemactobject1", "scriptitemactobject2",
        "scriptitemactparam", "scriptitemactship", "scriptitemdata", "scriptitemignore", "scriptitemtextdata", "scriptitemtoitem", "scriptrun", "sectorvisible",
        "seed", "sendstringtoclipboard", "serieleveln", "seriescount", "seriesnumincfg", "setcustommissileweaponstats", "setcustomweaponavailability", "setcustomweapondamagedata",
        "setcustomweaponprimarydata", "setcustomweaponse", "setcustomweaponshotdata", "setcustomweaponsizeandcost", "setdata", "setequipmentstats", "setfocus", "setname",
        "setparfromstring", "setparfromtxt", "setprogramm", "setrelationgroup", "setrelationplanet", "sft", "sharedeffect", "shareduse",
        "shipaddcustomshipinfo", "shipadddropitem", "shipangle", "shiparmor", "shiparts", "shipaveragedamage", "shipcalcparam", "shipcanjump",
        "shipcanrepaireq", "shipchangestar", "shipcntweapon", "shipcustomfaction", "shipcustomshipinfodata", "shipcustomshipinfodescription", "shipcustomshipinfoscount", "shipcustomshipinfotextdata",
        "shipdata", "shipdeletecustomshipinfo", "shipdestination", "shipdestroy", "shipdestroytype", "shipdroidrepair", "shipeqinslot", "shipface",
        "shipfind", "shipfindcustomshipinfobytype", "shipfreeexp", "shipfreeflight", "shipfreespace", "shipfuel", "shipfuellow", "shipgetbad",
        "shipgoods", "shipgoodsillegalonplanet", "shipgroup", "shiphealthfactor", "shiphealthfactorstatus", "shiphookpower", "shiphookrange", "shipimproveitems",
        "shipincurscript", "shipinfear", "shipingameevent", "shipinhole", "shipinhyperspace", "shipinnormalspace", "shipinpirateclan", "shipinplanet",
        "shipinprison", "shipinscript", "shipinstar", "shipispartner", "shipistakeoff", "shipitems", "shipjoin", "shipjoinsclan",
        "shipjointoscript", "shipjump", "shipkillfactionincursystem", "shipmoney", "shipname", "shipnearbyships", "shipnextpiraterankpoints", "shipnextrankpoints",
        "shiponsidepirateclan", "shiporder", "shiporderdata1", "shiporderdata2", "shiporderobj", "shipout", "shipowner", "shippartners",
        "shippicksitem", "shippilotrace", "shippiraterankpoints", "shipprotectability", "shipradarrange", "shipraiserank", "shiprank", "shiprankpoints",
        "shiprefit", "shiprefuel", "shiprepaireq", "shipscanerpower", "shipsetbad", "shipsetcoords", "shipsetpartner", "shipskill",
        "shipslots", "shipspecialbonuses", "shipspeed", "shipstanding", "shipstar", "shipstatistic", "shipstatus", "shipstatuseffect",
        "shipstrengthinaverageranger", "shipstrengthinbestranger", "shipsubrace", "shipsubtype", "shiptechlevelknowledge", "shipturnbeforeendorder", "shiptype", "shiptypen",
        "shipwealth", "shipweapon", "shopitems", "shortname", "showeffect", "showstaticeffect", "sin", "sizelarge",
        "sizesmall", "skipgreeting", "sound", "soundstart", "spawnmissile", "special", "specialtoequipment", "sqr",
        "sqrt", "staraddcustomstarinfo", "starangle", "staranglebetween", "starasteroids", "starbattle", "starcustomfaction", "starcustomstarinfodata",
        "starcustomstarinfoscount", "stardeletecustomstarinfo", "starenemythreatlevel", "starfindcustomstarinfobytype", "starfonimage", "starholes", "staritems", "starlisttoplanetlist",
        "starlisttotransitplanetlist", "starmapcenterview", "starmapcurposx", "starmapcurposy", "starmaplabel", "starmissiles", "starname", "starnearbystars",
        "starnearbystarsdist", "starowner", "starplanets", "starruins", "starseries", "starsetgraph", "starships", "startab",
        "startocon", "startrobots", "starttextquest", "startvideo", "stateis", "statusplayer", "stopmovingitem", "storageitemlocation",
        "storageitems", "str", "subcrackcost", "substr", "sudo", "switchtomirrorimage", "tail1", "talkbyai",
        "terron", "terrongrowlock", "terronlandinglock", "terrontostar", "terronweaponlock", "textbox", "textcolor", "textshadow",
        "textshadowcolor", "throw", "tips", "tipsstate", "toansi", "tounicode", "tranclucatordata", "transfership",
        "trim", "trimnumbers", "trucebetweenships", "uicheckelement", "uniquemm", "unknown", "updateformship", "uppercase",
        "upsurgegoods", "uselessitemcreate", "uselessitemdata", "uselessitemtext", "usetranclucator", "utilityfunctionslibinit", "weaponammunition", "weaponhit",
        "weaponmaxammunition", "weaponmods", "weaponport1", "weapontarget", "while", "zawarudo"
    }
)
